<a href="https://colab.research.google.com/github/umar052001/Deep-Learning-with-Tensorflow/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook, we're going to cover some of the most fundamental concepts of tensorflow.
Specifically, we're going to cover:
* Introduction to tensors.
* Getting information from tensors.
* Manipulating tensors.
* Tensors and Numpy.
* Using @tf.function (A way to speed up regular python functions).
* Using GPUs with Tensorflow (or TPUs)


## Introduction to Tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
#Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[3.,7.],
                             [10.,12.],
                             [12.,15.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 3.,  7.],
       [10., 12.],
       [12., 15.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Lets create a tensor
tensor = tf.constant([[[3,5,6],
                       [2,5,7]],
                       [[43,1,5],
                        [2,4,5]],
                      [[2,4,6],
                       [23,43,4]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 3,  5,  6],
        [ 2,  5,  7]],

       [[43,  1,  5],
        [ 2,  4,  5]],

       [[ 2,  4,  6],
        [23, 43,  4]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with direction
* Matrix: a 2 dimensional array of number
* tensor: n-dimensional array

### Creating tensors with `tf.variable()`

In [ ]:
changeable_tensor = tf.Variable([1,4])
unchangeable_tensor = tf.constant([1,4])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 4], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>)

In [ ]:
changeable_tensor[0] = 12

TypeError: ignored

In [ ]:
changeable_tensor[0].assign(8)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([8, 4], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(8)

AttributeError: ignored

### Create a random tensor

Tensors of some arbitrary size which contains some random numbers

In [ ]:
# Lets create random tensors
random_1= tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2= tf.random.Generator.from_seed(42)
random_2= random_2.normal(shape=(3,2))

In [ ]:
random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of tensors

In [ ]:
# Shuffle a tensor (inherent order doesn't effect learning)
not_shuffled = tf.constant([[10,3],
                            [12,4],
                            [2,4]])
not_shuffled.ndim

2

In [ ]:
shuffled_tensor = tf.random.shuffle(not_shuffled,seed=42)
shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  4],
       [12,  4],
       [10,  3]], dtype=int32)>

For tensors to be in same order we need to use both operational and global level seeds. `tf.random.set_seed(42)`

### Others ways to make tensors

In [ ]:
# Create a tensor of all ones
tf.ones([10,3])

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeros
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors
Difference of tensors and NumPy is that tensors can be run on GPU (much faster)

In [ ]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A
# X = tf.constant(some_matrix) capital for matrix/tensor
# y = tf.constant(vector) small for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
2*3*4

24

In [ ]:
A.ndim

3

### Getting information from tensors
Following attributes:
* Shape
* Rank
* Axis or Dimension
* Size


In [ ]:
# Create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Getting the attributes of our tensor
print("Data type of every element: ", rank_4_tensor.dtype)
print("Number of dimensions(rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along axis 0 : ", rank_4_tensor.shape[0])
print("Elements along last axis : ", rank_4_tensor.shape[-1])
print("Total elements : ", tf.size(rank_4_tensor))
print("Total elements : ", tf.size(rank_4_tensor).numpy())

Data type of every element:  <dtype: 'float32'>
Number of dimensions(rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along axis 0 :  2
Elements along last axis :  5
Total elements :  tf.Tensor(120, shape=(), dtype=int32)
Total elements :  120


### Indexing Tensors
Tensors can be indexed just like python lists.

In [ ]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
# Get first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:,:1,:2]

<tf.Tensor: shape=(1, 3, 1, 2), dtype=float32, numpy=
array([[[[0., 0.]],

        [[0., 0.]],

        [[0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimension)
rank_2_tensor = tf.constant([[1,2],
                             [2,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get last item of each of rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
# Add extra dimension in rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[2],
        [4]]], dtype=int32)>

In [ ]:
# Alternative for tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)  

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[2],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[2, 4]]], dtype=int32)>

# Manipulating Tensors (tensor operations)
**Basic Operations**

+,-,/*

In [ ]:
tensor = tf.constant([[1,3],
                      [43,6]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 13],
       [53, 16]], dtype=int32)>

In [ ]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 10,  30],
       [430,  60]], dtype=int32)>

In [ ]:
tensor -2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1,  1],
       [41,  4]], dtype=int32)>

In [ ]:
# We can also use the tensorflow built in functions
tf.multiply(tensor,3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  3,   9],
       [129,  18]], dtype=int32)>

In [ ]:
tf.add(tensor,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  5],
       [45,  8]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  3],
       [43,  6]], dtype=int32)>

**Matrix Multiplication**

In machine learning it is one of the most common operation.

Rules:
* Numbers from inner dimension must match.
* Shape of resulting matrix is same as outer dimension.

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  3],
       [43,  6]], dtype=int32)>

In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[130,  21],
       [301, 165]], dtype=int32)>

In [ ]:
# Matrix multiplication with pyhton operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[130,  21],
       [301, 165]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
X =tf.constant([[1,2],
               [2,4],
               [4,5]])
Y =tf.constant([[3,4],
               [6,6],
               [1,1]])

In [ ]:
tf.matmul(X, Y) # Failed because  rule failed

InvalidArgumentError: ignored

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[15,  6,  8],
       [30, 12, 16],
       [42, 21, 29]], dtype=int32)>

In [ ]:
# Transpose
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [2, 4, 5]], dtype=int32)>

In [ ]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 4],
       [4, 5]], dtype=int32)>

**The dot product**

Matrix multiplication is also refered as dot product

You can perform matrix multiplication using:

* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
X = tf.transpose(X)

In [ ]:
tf.tensordot(X,Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 20],
       [35, 37]], dtype=int32)>

### Change the datatype with tensors

In [ ]:
X.dtype

tf.int32

In [ ]:
X  = tf.cast(X,dtype=tf.float16) #reduced precesion
X

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 4.],
       [2., 4., 5.]], dtype=float16)>

### Aggregating Tensors

Multiple value to a single small value.

In [ ]:
C = tf.constant([-2,-5])

In [ ]:
tf.abs(C)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>

Following common four forms of aggregation:

* Get Minimum 
* Get Maximum 
* Get Mean 
* Get Sum 

In [ ]:
E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([59,  3, 50,  4,  5, 10,  1, 25, 48, 81, 50, 98, 43, 66, 10,  0,  8,
       27,  8,  5, 55, 38, 40,  4, 45, 95,  6, 35, 57, 76, 45,  7, 57,  0,
       94, 75, 43, 36, 45, 77, 56, 10, 75, 34, 73, 74,  4, 73, 67, 20])>

In [ ]:
tf.size(E)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [ ]:
E.shape

TensorShape([50])

In [ ]:
E.ndim

1

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=40>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=40>

In [ ]:
# Variance
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=858>

In [ ]:
#Standard diviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.2941>

### Find the positional maximum and minimum

Maximum or minimum in a row

In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimension)


In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
### One hot encoding

In [ ]:
some_list = [0,1,2,3]
tf.one_hot(some_list, depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list, depth=4, on_value="true", off_value="false")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'true', b'false', b'false', b'false'],
       [b'false', b'true', b'false', b'false'],
       [b'false', b'false', b'true', b'false'],
       [b'false', b'false', b'false', b'true']], dtype=object)>

### Squaring, log, square root

In [ ]:
H=tf.range(1,15)

In [ ]:
H

<tf.Tensor: shape=(14,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(14,), dtype=int32, numpy=
array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(14,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       , 3.1622777, 3.3166246, 3.4641016,
       3.6055512, 3.7416573], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(14,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851, 2.3978953, 2.4849067,
       2.5649493, 2.6390574], dtype=float32)>

### Tensors and Numpy
Tensorflow interacts beautifully with numpy arrays

Difference is tensors are for fast processing and run on tpu and gpu `tf.config.list_physical_device()`

In [ ]:
J = tf.constant(np.array([3.,4.,5.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 4., 5.])>

In [ ]:
np.array(J)

array([3., 4., 5.])

In [ ]:
type(np.array(J))

numpy.ndarray

In [ ]:
J.numpy()

array([3., 4., 5.])

In [ ]:
J.numpy()[0]

3.0

In [ ]:
J.dtype

tf.float64

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Tue Aug 30 21:27:30 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P0    28W /  70W |    286MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------